image: "rust:latest"

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends build-essential cmake

test:cargo:
    script:
    - rustc --version && cargo --version # Print version info for debugging
    - time cargo test --verbose --release # Don't paralalize to make errors more readable
