[package]
name = "chip8"
version = "0.1.0"
authors = ["Agoston Szepessy <agszepp@gmail.com>"]
edition = "2021"

[dependencies]
derive_builder = "0.20"
measurements = "0.11"
rand = "0.8"
thiserror = "1.0"

[dependencies.sdl2]
version = "0.36"
features = ["bundled"]
