[package]
name = "chip8"
version = "0.1.0"
authors = ["Agoston Szepessy <agszepp@gmail.com>"]
edition = "2021"

[dependencies]
measurements = "0.11.0"
rand = "0.8.5"
thiserror = "1.0"

[dependencies.sdl2]
version = "0.36"
features = ["bundled"]
