[package]
name = "chip8"
version = "0.1.0"
authors = ["Agoston Szepessy <agszepp@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.8.5"

[dependencies.sdl2]
version = "0.36"
features = ["bundled"]
